import { defineStore } from 'pinia'

export const useProductStore = defineStore('product', {
  state: () => ({
    groups: [
      { id: 1, name: 'Meat' },
      { id: 2, name: 'Vegetable' },
      { id: 3, name: 'Fruit' },
    ],
    categories: [
      { id: 1, name: 'Fruits', image: '/images/Apple.png', productCount: 5, color: '#FF6B6B' },
      {
        id: 2,
        name: 'Vegetables',
        image: '/images/Vegetable.png',
        productCount: 3,
        color: '#4ECDC4',
      },
      { id: 3, name: 'Snacks', image: '/images/snack.png', productCount: 2, color: '#45B7D1' },
      { id: 4, name: 'Dairy', image: '/images/Cake&Milk.png', productCount: 1, color: '#FFA07A' },
      {
        id: 5,
        name: 'Electronics',
        image: '/images/Headphone.png',
        productCount: 1,
        color: '#98D8C8',
      },
    ],
    promotions: [
      {
        id: 1,
        title: 'Fresh Onions',
        color: '#f0e8d5',
        image: '/images/Onion-Banner.png',
        imageAlt: 'Fresh Onions Banner',
        buttonColor: '#42B678',
        url: '/',
        class: 'banner-onions',
      },
      {
        id: 2,
        title: 'Breakfast Special',
        color: '#f3e8e8',
        image: '/images/Cake&Milk.png',
        imageAlt: 'Breakfast Special Banner',
        buttonColor: '#ffa500',
        url: '/',
        class: 'banner-breakfast',
      },
      {
        id: 3,
        title: 'Organic Products',
        color: '#e7eaf3',
        image: '/images/BacketOfVegetable.png',
        imageAlt: 'Organic Products Banner',
        buttonColor: '#42B678',
        url: '/',
        class: 'banner-organic',
      },
    ],
    products: [
      {
        id: 1,
        name: 'Apple',
        rating: 4.5,
        size: 'Medium',
        image: '/images/Apple.png',
        price: 1.99,
        promotionAsPercentage: 0,
        categoryId: 1,
        instock: true,
        countSold: 150,
        group: 1,
      },
      {
        id: 2,
        name: 'Burger',
        rating: 4.2,
        size: 'Large',
        image: '/images/Burger.png',
        price: 5.99,
        promotionAsPercentage: 10,
        categoryId: 3,
        instock: true,
        countSold: 200,
        group: 1,
      },
      {
        id: 3,
        name: 'Headphone',
        rating: 4.8,
        size: 'One Size',
        image: '/images/Headphone.png',
        price: 49.99,
        promotionAsPercentage: 15,
        categoryId: 5,
        instock: false,
        countSold: 50,
        group: 2,
      },
      {
        id: 4,
        name: 'Kiwi',
        rating: 4.0,
        size: 'Small',
        image: '/images/Kiwi.png',
        price: 2.49,
        promotionAsPercentage: 5,
        categoryId: 1,
        instock: true,
        countSold: 80,
        group: 1,
      },
      {
        id: 5,
        name: 'Orange',
        rating: 4.3,
        size: 'Medium',
        image: '/images/Orange.png',
        price: 1.49,
        promotionAsPercentage: 0,
        categoryId: 1,
        instock: true,
        countSold: 120,
        group: 1,
      },
      {
        id: 6,
        name: 'Peach',
        rating: 4.6,
        size: 'Large',
        image: '/images/Peach.png',
        price: 2.99,
        promotionAsPercentage: 8,
        categoryId: 1,
        instock: true,
        countSold: 90,
        group: 1,
      },
      {
        id: 7,
        name: 'Strawberry Milk',
        rating: 4.1,
        size: '500ml',
        image: '/images/StrawberryMilk.png',
        price: 3.49,
        promotionAsPercentage: 12,
        categoryId: 4,
        instock: true,
        countSold: 60,
        group: 1,
      },
      {
        id: 8,
        name: 'Black Plum',
        rating: 4.4,
        size: 'Medium',
        image: '/images/Black-plum.png',
        price: 2.79,
        promotionAsPercentage: 0,
        categoryId: 1,
        instock: false,
        countSold: 30,
        group: 1,
      },
    ],
  }),
  getters: {},
  actions: {
    setGroups(groups: any[]) {
      this.groups = groups
    },
    setCategories(categories: any[]) {
      this.categories = categories
    },
    setPromotions(promotions: any[]) {
      this.promotions = promotions
    },
    setProducts(products: any[]) {
      this.products = products
    },
  },
})
